### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by JiaKaiGH** [blockchain-group/DIRECTGO#1]
1. In most s-type algorithm, '100*" is missing when calculating 'VAL.perror' in function 'Arewedone'.

if OPTI.TESTflag == 1               % Check for stop condition
    if OPTI.globalMIN ~= 0            % Calculate error if globalmin known
        VAL.perror = (Fmin - OPTI.globalMIN)/abs(OPTI.globalMIN);
    else
        VAL.perror = Fmin;
    end
    if VAL.perror < OPTI.TOL
        fprintf('Minima was found with Tolerance: %4i', OPTI.TOL);
        VAL.perror = -10;
    end
else
    VAL.perror = 10;
end

2. 'VAL.time = toc;' should write befor 'if', otherwise the forth column of history would be 0 when OPTI.showITS~=1.

if OPTI.showITS == 1                % Show iteration stats
    VAL.time = toc;
    fprintf(...
    'Iter: %4i   f_min: %15.10f    time(s): %10.05f    fn evals: %8i\n',...
        VAL.itctr, Fmin, VAL.time, VAL.I);
end

**Comment by blockchain-group** [comment]
You are right - thank you for pointing this out!
